name: Check TwitchLib.PubSub.Example

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main ]

jobs:
  check-buildstatus:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build TwitchLib.PubSub.Example
      run: dotnet build --no-restore